# see https://github.com/scalameta/sbt-native-image#generate-native-image-from-github-actions
name: Native Image
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  build-native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            uploaded_filename: scitzen-x86_64-pc-linux
            local_path: target/native-image/awslambda
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11
      - run: git fetch --tags || true
      - name: build builder docker file
        run: sudo docker build -t awscompile .
        shell: bash
      - name: build native image in docker
        run: sudo docker run -v $(pwd):/proj awscompile
        shell: bash
      - uses: actions/upload-artifact@master
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
